name: flutter_js
description: A Javascript engine to use with flutter. 
  It uses Quickjs on Android and JavascriptCore on IOS
version: 0.6.0+0
homepage: https://github.com/abner/flutter_js
repository: https://github.com/abner/flutter_js

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  ffi: "^1.0.0"
  http: ^0.13.4
  sync_http: ^0.3.0

dev_dependencies:
  test: ^1.17.3

plugin:
  platforms:
    android:
      package: io.abner.flutter_js
      pluginClass: FlutterJsPlugin
    ios:
      pluginClass: FlutterJsPlugin
    linux:
      #default_package: flutter_js_linux_win
      pluginClass: FlutterJsPlugin
    macos:
      pluginClass: FlutterJsPlugin
    # windows:
    #   default_package: flutter_js_linux_windows
    windows:
      pluginClass: FlutterJsPlugin

flutter:
  plugin:
    platforms:
      android:
        package: io.abner.flutter_js
        pluginClass: FlutterJsPlugin
      ios:
        pluginClass: FlutterJsPlugin
      linux:
        #default_package: flutter_js_linux_win
        pluginClass: FlutterJsPlugin
      macos:
        pluginClass: FlutterJsPlugin
      # windows:
      #   default_package: flutter_js_linux_windows
      windows:
        pluginClass: FlutterJsPlugin
